### PR TITLE
feat(budget-tool): custom card drawing input

### LINKED ISSUE #230: Feat: Custom card draw
**Is your feature request related to a problem? Please describe.**
Previously we had a system where users could draw custom budget cards when a given activity or input is not available. This was removed due to technical incompatibility (3rd party package used wasn't maintained). 

We would like to bring back the option for users to draw their own visual representations for cards that do not exist in the project.  This feature would initially be used in the budget tool, but likely extended to be used across most other tools as well.

**Describe the solution you'd like**
- Add [perfect-freehand](https://github.com/steveruizok/perfect-freehand) package
- Create a standalone `picsa-drawing` component in `libs\shared\src\features\drawing` that provides a minimal ui for drawing
- Integrate the component into `apps\picsa-tools\budget-tool\src\app\components\card\card-new\card-new-dialog.html`

**Describe alternatives you've considered**
After looking at a few options, I think the best drawing library suited to our needs would be [perfect-freehand](https://github.com/steveruizok/perfect-freehand)

The interface for this tool is nice and simple, and output looks more natural than [tldraw](https://www.tldraw.com) or drawingboard.js

The most popular drawing library I could find is excalidraw. This has a lot more featuers (infinite whiteboard, text, image, shapes etc.), however it actually uses perfect-freehand to manage freestyle drawing anyway so if we later wanted more features it should be a reasonable migration process.

**Additional context**
Perfect freehand demo available at: https://www.perfectfreehand.com/

Getting a smooth workflow to work on a component that will only be used in a popup window is a bit tricky, you may find it easier to first work on the component first within a new page, e.g. `/budget/card-editor`

### PR DESCRIPTION
**Pull request by FaithDaka**
## Description
Adds new drawing input component and integrates with budget tool custom cards

closes #230
## Preview

_Link to app preview if relevant_

## Screenshots / Videos

[Screenity video - Jun 5, 2024.webm](https://github.com/e-picsa/picsa-apps/assets/10515065/0686291f-2427-4867-a4e0-2fecb90d727e)

### CODE REVIEW

**Comment by chrismclarke** [comment]
@FaithDaka - thanks for sharing the draft PR, it took a bit of working out but I think I finally figured out what the issue is and have opened PR #271 targeting this branch to fix the issue. Feel free to merge it in if it makes sense to you. 

In terms of next steps I think the main task will be to support multiple paths, so that when the user releases their pointer the path is finalised and the user can start a new path on next mouse down. The svg element will then need to use an `@for` loop to render each of the paths on the page. We will also want to replace the button component I've added with some sort of div/svg that renders the current svg, and when clicked opens up the svg editor.

If you think that is better for a follow-up PR I think you could just comment out the element on the current budget testing page and we should be able to merge this in as a base component and build on in follow-up issue.

We may also want to consider some stretch goals like an undo/redo button for drawn paths, as well as a clear button to start new. Further features like colour picker, eraser would probably be much lower priority.

**Comment by FaithDaka** [comment]
https://github.com/e-picsa/picsa-apps/assets/53012890/3578c860-bd6e-45fd-9cf7-41ae9a731732

**Comment by FaithDaka** [comment]
Fixed the svg path bug. 
Pending bug: undo and redo funtionality
https://github.com/e-picsa/picsa-apps/assets/53012890/f8e00d2c-ddbd-49f7-8737-35a8c873b8d8

**Comment by FaithDaka** [comment]
Fixed the svg path bug. 
Pending bug: undo and redo functionality

https://github.com/e-picsa/picsa-apps/assets/53012890/31caeca9-8c57-48e3-9ca6-5fc98f501f84

**Review by chrismclarke — COMMENTED** [review]
Thanks @FaithDaka - working much better now, also like the undo/redo feature you've included.

I started testing and noticed a few performance issues on mobile. I've addressed some of them by merging in #284

There's still a few minor updates I want to add as part of the review process so will try come back to it later today. 

- [x] fix storing final path for future render/edit
- [x] further testing on mobile
- [ ] remove test button and integrate into budget tool card pages

But overall I think looking really nice do I don't think any more work will be required from your side. Thanks again

**Review by chrismclarke — APPROVED** [review]
I've now merged #285 to integrate directly into the budget tool custom card drawing component and tidied up the output handling a bit - so I think should now be good to go (updated video in main description). Thanks again for all the help on this one

**Pull request merged**
