### PR TITLE
ft(farmer-activity) Support for photo storage

### PR DESCRIPTION
**Pull request by OchiengPaul442**
**Updated Screenshots**
**Demo - adding photos to farmer content**

[Screenity video - Jul 28, 2024.webm](https://github.com/user-attachments/assets/6cb19308-cc64-4e1e-9125-38600bbd8a77)

**Demo - photos debug page (available at /photos)**
localhost_4200_photos(Picsa)

---
## Description
- Implemented a schema for photo storage.
- Developed a `photo-list` component for displaying all uploaded photos.
- Moved the photo-input component to the shared features folder for better code organization.
- Enhanced the schema with an `activity `property to filter images by different` farm-activity` categories.
- Validated that images are correctly filtered across different farm activities though they are not being displayed due to issue with getting url.

## Discussion
- Photos have been successfully uploaded and stored in the database. Initially, the photos were stored in base64 format under the photoData property. While this method was functional, it led to slower performance and could potentially be costly in the long run due to the large size of base64 formatted data. To optimize performance and efficiency, the storage method was later updated to use attachments, following the guidelines provided in the RxDB documentation.
- Encountered issues with retrieving the attachment URI using the getFileAttachmentURI method, which is needed to display the stored images.

## NB:
- A video demonstration is not available due to ongoing issues with retrieving the URL from the attachments. Assistance is required to resolve this issue.

## Preview

_Link to app preview if relevant_

## Screenshots / Videos

_Include at least 1-2 screenshots of videos if visual changes_

### CODE REVIEW

**Comment by OchiengPaul442** [comment]
Hey @chrismclarke,
I’ve encountered an issue while trying to retrieve the image URI for displaying the images from the attachments. Although the images are being uploaded successfully, I’m having trouble retrieving the URI using the existing getFileAttachmentURI method. It seems to return NULL. (Not sure if the issue is with the data being passed)

I’ve reviewed the code, but I haven’t been able to identify the problem. I considered making changes, but I’m hesitant as this method is used elsewhere in the code and I don’t want to introduce new issues.

I would greatly appreciate your assistance on this issue. Thanks

image

**Review by chrismclarke — APPROVED** [review]
Thanks @OchiengPaul442 

I was able to investigate the issue you were experiencing, it is because the attachment service was always designed around the resources system, and assigning attachment ids based on the `doc.filename` property of resource docs which doesn't exist for photos.
So I've updated to fallback to the doc id as part of ec7817e

I've also added 1ed9b84 to update the schema to store a separate `album` property to make it easier to organise photos within some sort of collection/grouping (and a few other minor schema changes). I haven't added a migration so you will need to clear the cache on your device when next working on it to accept the schema changes without throwing an error

I like that you had created separate components for photo input and list, I've further separated these out to include a photo view component as part of c61e355, and done some tidying to move the relevant code into each component

I've also made some updates to the photo service to make it easeir to automatically subscribe to the list of all photos available within the db using the newer angular signals interface (see 5109867)

Finally I merged the latest changes from master to integrate with the newer `farmer-content` tool (previously `farmer-activity` which is now deprecated and will be removed shortly), via d88d815. See updated demo in the PR description

So overall I think looking pretty good and I'd definitely be keen to get things merged in how they currently are. If you'd get a chance I'd appreciate if you could test on android to see if working as expected. I've also added issue #305 as a follow-up issue to improve the photo-view component (would be nice if possible to open the photo on tap for a full-screen view experience like similar gallery apps - right now the photos only appear at a smaller fixed size). I think it might be good to prioritise this issue ahead of others you may also be working on.

**Comment by OchiengPaul442** [comment]
Thanks @chrismclarke, I have been following the changes made to understand where I was going wrong, especially on the [1ed9b84](https://github.com/e-picsa/picsa-apps/pull/292/commits/1ed9b84ebb0ede3687852e9fce0df5ca5da9e6fc) and https://github.com/e-picsa/picsa-apps/commit/5109867680967e3ec840bffb095984f34287b2cd as I was mostly getting errors on those sections when testing. Also thanks for merging the conflicts to this branch I am not sure yet why I am not able to resolve them locally even after refreshing and updating from the main branch though ?

**Comment by chrismclarke** [comment]
> Thanks @chrismclarke, I have been following the changes made to understand where I was going wrong, especially on the [1ed9b84](https://github.com/e-picsa/picsa-apps/pull/292/commits/1ed9b84ebb0ede3687852e9fce0df5ca5da9e6fc) and [5109867](https://github.com/e-picsa/picsa-apps/commit/5109867680967e3ec840bffb095984f34287b2cd) as I was mostly getting errors on those sections when testing. Also thanks for merging the conflicts to this branch I am not sure yet why I am not able to resolve them locally even after refreshing and updating from the main branch though ?

A bit strange, I've just merged the PR so I think probably best to just revert back to the main branch (discarding any other local changes) and creating a new branch for the next issue you work on.

Speaking of which, I've added https://github.com/e-picsa/picsa-apps/issues/305 as a follow-up issue to improve the photo-view component (would be nice if possible to open the photo on tap for a full-screen view experience like similar gallery apps - right now the photos only appear at a smaller fixed size). 

I think it might be good to prioritise this issue ahead of others you may also be working on if possible.

**Comment by OchiengPaul442** [comment]
> > Thanks @chrismclarke, I have been following the changes made to understand where I was going wrong, especially on the [1ed9b84](https://github.com/e-picsa/picsa-apps/pull/292/commits/1ed9b84ebb0ede3687852e9fce0df5ca5da9e6fc) and [5109867](https://github.com/e-picsa/picsa-apps/commit/5109867680967e3ec840bffb095984f34287b2cd) as I was mostly getting errors on those sections when testing. Also thanks for merging the conflicts to this branch I am not sure yet why I am not able to resolve them locally even after refreshing and updating from the main branch though ?
> 
> A bit strange, I've just merged the PR so I think probably best to just revert back to the main branch (discarding any other local changes) and creating a new branch for the next issue you work on.
> 
> Speaking of which, I've added #305 as a follow-up issue to improve the photo-view component (would be nice if possible to open the photo on tap for a full-screen view experience like similar gallery apps - right now the photos only appear at a smaller fixed size).
> 
> I think it might be good to prioritise this issue ahead of others you may also be working on if possible.

Sure thing, will take on #305.

**Pull request merged**
